# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master
  pull_request:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The type of runner that the job will run on
  pre-merge-check:
    runs-on: ubuntu-latest
    name: pre-merge-check
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6.10]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: generating riscof new version
      run: |
        ./version_check.sh
        pip3 install --upgrade pip
        pip3 install -r riscof/requirements.txt -U
        python3 setup.py sdist
#   running:
#     runs-on: ubuntu-latest
#     name: running_with_new_riscof
#     strategy:
#       fail-fast: false
#       matrix:
#         python-version: [3.6.10]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python ${{matrix.python-version}}
#       uses: actions/setup-python@v2
#       with:
#         python-version: ${{matrix.python-version}}
#     - name: setting up riscof new version
#       run: |
#         ./version_check.sh
#         pip3 install --upgrade pip
#         pip3 install -r riscof/requirements.txt -U
        
#   post-deploy-check:
